**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [4]:
import numpy as np

In [7]:
arr_list = np.array([[5, 15, 25, 35, 45]])
arr_0 = np.zeros((7,))
arr_1 = np.ones((6,))
arr_arange = np.arange(10, 20, 1)

arr_list, arr_0, arr_1, arr_arange

(array([[ 5, 15, 25, 35, 45]]),
 array([0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1.]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))


---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [9]:
arr = np.arange(12, 61, 12)
arr

array([12, 24, 36, 48, 60])

In [17]:
display(arr * 2)
display(arr + 10)
display(arr ** 2)
display(np.sqrt(arr))

array([ 24,  48,  72,  96, 120])

array([22, 34, 46, 58, 70])

array([ 144,  576, 1296, 2304, 3600])

array([3.46410162, 4.89897949, 6.        , 6.92820323, 7.74596669])


---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [19]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
data

array([18, 27, 33, 41, 52, 68, 79])

In [25]:
display(data.mean())
display(data.min())
display(data.max())
display(data.sum())

print(f"Середнє: {np.mean(data)}")
print(f"Мінімум: {np.min(data)}")
print(f"Максимум: {np.max(data)}")
print(f"Сума всіх елементів: {np.sum(data)}")

45.42857142857143

18

79

318

Середнє: 45.42857142857143
Мінімум: 18
Максимум: 79
Сума всіх елементів: 318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [30]:
arr = np.array([15, 22, 35, 44, 58, 67])
arr

array([15, 22, 35, 44, 58, 67])

In [31]:
print(f"Перший елемент: {arr[0]}")
print(f"Останній елемент: {arr[-1]}")
print(f"Елементи з індексами 1 до 3: {arr[1:3]}") ## не включно
print(f"Елементи більші за 40: {arr[arr>40]}")

Перший елемент: 15
Останній елемент: 67
Елементи з індексами 1 до 3: [22 35]
Елементи більші за 40: [44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [33]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [40]:
display(matrix.shape)
display(matrix[:,0]) ## перший рядок не за індексом
display(matrix[1,:]) ## друга колонка не за індексом
print(f'Сума всіх елементів: {np.sum(matrix)}')
print(f'Середнє всіх елементів: {np.mean(matrix)}')

(3, 3)

array([ 2,  8, 14])

array([ 8, 10, 12])

Сума всіх елементів: 90
Середнє всіх елементів: 10.0
